
export enum Tipo {
  ANIME = "ANIME",
  MANGA = "MANGA",
  MANHUA = "MANHUA",
  MANHWA = "MANHWA",
  SERIE = "SERIE",
  FILME = "FILME",
  NOVEL = "NOVEL",
  LIVRO = "LIVRO",
}

export enum Status {
  PLANEJADO = "PLANEJADO",
  EM_PROGRESSO = "EM_PROGRESSO",
  PAUSADO = "PAUSADO",
  CONCLUIDO = "CONCLUIDO",
  ABANDONADO = "ABANDONADO",
}
