import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: '#f8fafc',
    },
    bottomModalContainer: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    bottomModal: {
      backgroundColor: '#fff',
      padding: 24,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 10,
    },
    searchContainer: {
      marginBottom: 16,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: '#e2e8f0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    icon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      height: 40,
      color: '#334155',
      fontSize: 16,
    },
    title: {
      fontSize: 20,
      fontWeight: '600',
      color: '#1e293b',
      marginBottom: 16,
    },
    flatlist: {
      width: '100%',
    },
    obraItem: {
      marginBottom: 16,
    },
    cardContent: {
      flexDirection: 'row',
      padding: 16,
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    obraImage: {
      width: 80,
      height: 120,
      borderRadius: 8,
      backgroundColor: '#f1f5f9',
    },
    obraInfo: {
      flex: 1,
      marginLeft: 12,
    },
    titulo: {
      fontSize: 16,
      fontWeight: '600',
      color: '#1e293b',
      marginBottom: 4,
    },
    descricao: {
      fontSize: 14,
      color: '#64748b',
      marginBottom: 8,
      lineHeight: 20,
    },
    autor: {
      fontSize: 12,
      color: '#64748b',
      marginBottom: 2,
    },
    tipo: {
      fontSize: 12,
      color: '#64748b',
      marginBottom: 2,
    },
    generos: {
      fontSize: 12,
      color: '#64748b',
      fontStyle: 'italic',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
      width: '90%',
      maxWidth: 400,
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: '#1e293b',
      marginBottom: 20,
      textAlign: 'center',
    },
    modalInput: {
      height: 48,
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 12,
      paddingHorizontal: 16,
      marginBottom: 16,
      backgroundColor: '#f8fafc',
      color: '#334155',
      fontSize: 16,
    },
    picker: {
      width: '100%',
      height: 48,
      backgroundColor: '#f8fafc',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#e2e8f0',
      marginBottom: 16,
    },
  });

  export default styles;